# Site settings
title: 김기현의 블로그
description: '백엔드 개발자를 목표로 공부합니다'
url: 'https://KimKiHyun0206.github.io'
baseurl: '/'


author:
  name: 'KimKiHyun0206'
  email: rlarlgus0206@naver.com
  twitter_username:
  facebook_username:
  github_username: KimKiHyun0206
  linkedin_username: